name: CI/CD for Engineering College App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Dhivya@12345
          MYSQL_DATABASE: ecollege
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 22
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '22'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.9.6

      - name: Build WAR with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t college-app:latest .

      - name: Run docker-compose
        run: docker-compose up -d

      - name: Wait for application to start
        run: sleep 30

      - name: Test Application Endpoint
        run: |
          curl --fail http://localhost:8080 || exit 1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and push Docker image
        run: |
          docker tag college-app:latest ${{ secrets.DOCKER_USERNAME }}/college-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/college-app:latest
