services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: engineeringcollegeapplication
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/ecollege?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Dhivya@12345
    ports:
      - "8080:8080"
    networks:
      - spring-net

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Dhivya@12345
      MYSQL_DATABASE: ecollege
    ports:
      - "3307:3306"
    networks:
      - spring-net
    command: --default-authentication-plugin=mysql_native_password

networks:
  spring-net:
    driver: bridge
