services:
  - type: web
    name: collegeapp
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://college-mysql:3306/ecollege?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: Dhivya@12345

databases:
  - name: college-mysql
    databaseName: ecollege
    user: root
    password: Dhivya@12345
