name: collegeapp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ecollege
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'adopt'
        cache: maven

    - name: Set up Maven
      run: mvn --version

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Docker build
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/collegeapplication .

    - name: Docker Hub login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/collegeapplication
